CREATE TABLE IF NOT EXISTS TB01_CATEGORIA(
    CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (50) NOT NULL
);

INSERT INTO TB01_CATEGORIA (NOME) VALUES
('Lazer'),
('Alimentação'),
('Supermercado'),
('Farmácia'),
('Outros');
